<<<<<<< HEAD
lsi: false
safe: true
source: bquarant.github.com
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
=======
name: bqmd.org
markdown: kramdown

theme: jekyll-theme-minimal
>>>>>>> 12721125f58092d8703e9c4cac17096c285ae2d0
